apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend-service
    app: stockprice-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8000
  selector:
    name: backend-pod
    app: stockprice-app