apiVersion: v1
kind: Service
metadata:
  name: cache-service
  labels:
    name: cache-service
    app: stockprice-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8080
  selector:
    name: cache-pod
    app: stockprice-app