apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deploy
  labels:
    name: cache-deploy
    app: stockprice-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: cache-pod
     app: stockprice-app
  template:
   metadata:
    name: cache-pod
    labels:
      name: cache-pod
      app: stockprice-app
   spec:
    containers:
    - name: stockprice-app
      image: 22piston/stock-price-cache-app:latest
      ports:
        - containerPort: 80
    nodeSelector:
      eks.amazonaws.com/nodegroup: t3_medium-node_privategroup
