apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: stockprice-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
  selector:
    name: frontend-pod
    app: stockprice-app